
export const KnownCrawlerUAs = {
  googlebot: 'Googlebot',
  bingbot: 'Bingbot',
  adsbot: 'AdsBot-Google',
  msnbot: 'MSNBot',
  duckduckbot: 'DuckDuckBot',
  yandexbot: 'YandexBot',
  baiduspider: 'Baiduspider',
  twitterbot: 'Twitterbot',
  facebookexternalhit: 'facebookexternalhit',
  linkedinbot: 'LinkedInBot',
  slackbot: 'Slackbot',
  telegrambot: 'TelegramBot',
  applebot: 'Applebot',
  pinterestbot: 'Pinterest',
  whatsapp: 'WhatsApp',
  skypeuripreview: 'SkypeUriPreview',
  skypebot: 'Skype-App',
};


export const KnownAgentAis = {
  okhttp: /okhttp/i,
  curl: /curl/i,
  wget: /wget/i,
  headlessChrome: /HeadlessChrome/i,
  pythonHTTP: /python-requests/i,
  nodeHTTP: /node-fetch/i,
  puppeteer: /puppeteer/i,
  phantomJS: /PhantomJS/i,
  googleReadAloud: /Google-Read-Aloud/i,
  googleTranslate: /Google-Translate/i,
  googlePageSpeed: /Google-Page-Speed/i,
  byteSpider: /ByteSpider/i,
  pingdom: /Pingdom/i,
  uptimerobot: /UptimeRobot/i,
  semrush: /SemrushBot/i,
  ahrefs: /AhrefsBot/i,
  mj12: /MJ12bot/i,
  dotbot: /DotBot/i,
  rogerbot: /Rogerbot/i,
  iframely: /iframely/i,
  nessus: /Nessus/i,
  postman: /PostmanRuntime/i,
  zapier: /Zapier/i,
};
