services:
  docker:
    image: alpine:3.19
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - GOOGLE_PROJECT_ID="palm-finance-web-app"
  api:
    build: .
    ports:
      - ":3030"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - GOOGLE_PROJECT_ID="palm-finance-web-app"