name: CI
on: [push, pull_request]
# Needed for nx-set-shas when run on the main branch
permissions:
  actions: write
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6'
      - run: npm install -g nx
      - run: npm install -g pnpm
      - run: pnpm i
      - run: source .envrc
      # Change APP_NAME to the name of your app
      - run: pnpm exec nx lint APP_NAME --verbose --configuration=production --parallel --fix
      - run: pnpm exec nx build APP_NAME --verbose --configuration=production --parallel
      - uses: actions/upload-artifact@v4
        with:
          name: nx-cache
          path: ~/.nx/cache/terminalOutputs
          zip: true